---
title: "Your Project Title"
author: "Samira Shirazy, Rebecca Chan, Dinah Bahta and Emily Olshan"
date: "2/18/2022"
output: html_document
---

``` {r setup, include = FALSE}

# Load necessary libraries
library("dplyr")
library("tidyr")
library("ggplot2")
library("stringr")
library("knitr")

```

``` {r line_chart}
source("../source/line_chart.R")
ggplot(homelessness_by_year, aes(x = year, y = yearly_total)) +
  scale_y_continuous(labels = scales::comma) +
  geom_area(
    color = "black",
    alpha = .5,
    size = 2,
    fill = 8
  ) +
  geom_point(
    size = 2,
    color = "red"
  ) +
  labs (
    title = "Homeless Population in U.S. by year",
    subtitle = "Sum of the homelessness populations from 2007 to 2016",
    x = "Year",
    y = "Population Sum",
    color = "Urbanity"
)
```

``` {r bar_chart}
source("../source/bar_chart.R")
ggplot(homeless_pop) +
  geom_col(mapping = aes(year, pop, fill = area)) +
  ylab("Homeless Population") +
  scale_fill_discrete(labels = c("total city homeless", "total rural homeless", "total suburban homeless", "total urban homeless")) +
  labs(fill = "Community Type", title = "Homeless Pop over Time \n by Community Type")
```

``` {r Scatter_Plot}
source("../source/Scatter.Plot.R")
ggplot(data = the_homeless) +
  geom_point(
    mapping = aes(x = Year, y = Count, color = State), alpha = .9, size = 3
  ) +
  scale_color_manual(values=c("Purple","Green")
  ) +
  theme(axis.title = element_text(face="bold", size=13)
  ) +
  labs(
    
  title = "Total Homeless Population of (New York vs. Washington State)",
  subtitle = "(Total Population By Year)",
  x = "Year (2007-2016)",
  y = "Total Homeless Count",
  color = "Location") +
  theme(plot.title = element_text(face ="bold", size=15)
  )
```